name: MonoChat
main: japura.MonoChat.MonoChat
version: 2.0
commands:
    monochat:
        description: primary monochat command. use /monochat help for info
        usage: /monochat help

permissions:
	monochat.admin:
		description: permission to use monochat admin commands
		default: false
