name: MonoMobs
main: japura.MonoMobs.MonoMobs
version: 2.0
commands:
    monomobs:
        description: primary MonoMobs command. use /monomobs help for info
        usage: /monomobs help

permissions:
	monomobs.admin:
		description: permission to use monomobs admin commands
		default: false
