name: MonoMobs
main: japura.MonoMobs.MonoMobs
version: 2.0
commands:
    monomobs:
        description: primary MonoMobs command. use /monomobs help for info
        usage: /monomobs
        permission: Monomobs
        permissions-message: You don't have permission
