name: NoWither
main: japura.NoWither.NoWither
version: 2.0
commands:
        nowither:
                description: Nowither control command. use /nowither help for info
                usage: /nowither help

permissions:
        nowither.admin:
                description: access to the /nowither command for admins
                default: false
