name: MonoCities
main: japura.MonoCities.MonoCities
version: 0.01
load: startup
commands:
    MonoCities:
        description: primary MonoCities command. use /MonoCities help for info
        usage: /MonoCities
        permission: monocities
        permissions-message: You don't have permission