name: MonoBugs
main: japura.MonoBugs.MonoBugs
version: 2.0
commands:
    bug:
        description: primary bug command. use /bug help for info
        usage: /bug help

permissions:
    monobugs:
        description: the /bug command 
        default: true
    monobugs.admin:
        description: Full admin permissions
        default: false
        children:
            monobugs: true
