ClaimSize: 8
YAxisClaim: false
Tribe Spawn: false
MOTD: Welcome to Japura.net!
Disband after time: true
Days before disband: 60
mongo host: localhost
mongo port: 27017
mongo database: MonoMods
mongo tribe table: tribes
mongo emerald table: emeralds
mongo diamond table: diamonds
mongo kit table: kit

