name: Tribes
main: japura.Tribes.Tribes
version: 1.00
author: monofuel

commands:
    t:
        description: primary Tribes command. use /t help for info
        usage: /t help to display help
        aliases: tribes
        permission: tribes
        permissions-message: You don't have permission to use tribes
    tadmin:
        description: Admin functions for tribes
        usage: /tadmin
        permission: tribes.admin
        permissions-message: You don't have admin permissions for tribes
        
permissions:
    tribes:
        description: Basic tribes permissions 
        default: true
    tribes.admin:
        description: Full admin permissions
        default: false
        children:
            tribes: true