name: MonoCities
main: japura.MonoCities.MonoCities
version: 2.0
commands:
    MonoCities:
        description: primary MonoCities command. use /MonoCities help for info
        usage: /MonoCities help

permissions:
    monocities.admin:
        description: permission to use monocities admin commands
        default: false
