name: MonoLocks
main: japura.MonoLocks.MonoLocks
version: 2.0
commands:
    MonoLocks:
        description: primary MonoLocks command. use /MonoLocks help for info
        usage: /MonoLocks help

permissions:
	monolocks.admin:
		description: permission to use monolocks admin commands
		default: false
