name: MonoPerms
main: japura.MonoPerms.MonoPerms
version: 2.0
commands:
    perm:
        description: primary MonoPerms command. use /perm help for info
        usage: /perm help

permissions:
        monoperms.admin:
                descrption: permission to use monoperms admin commands
                default: false
