name: MonoPerms
main: japura.MonoPerms.MonoPerms
version: 0.01
commands:
    perm:
        description: primary MonoPerms command. use /perm help for info
        usage: /perm help

permissions:
        monoperms:
                descrption: permission to use monoperms
                default: false
